In [1]:
import cv2

In [4]:
img_gray = cv2.imread("smallgray.png", 0)
img_gray

array([[ 85, 146, 203,  85,  24],
       [221,  85, 157, 177, 177],
       [ 24,  24, 146, 177, 203]], dtype=uint8)

In [6]:
img_colour = cv2.imread("smallcolour.png", 1)
img_colour

array([[[102, 102, 253],
        [107,  93,  14],
        [ 65, 149,  61],
        [ 54,  54, 255],
        [116, 125, 143]],

       [[107,  93,  14],
        [243, 125, 217],
        [102, 102, 253],
        [243, 125, 217],
        [ 99, 228, 233]],

       [[ 65, 149,  61],
        [ 24,  24,  24],
        [164,  32,  63],
        [ 99, 228, 233],
        [ 59,  96,  26]]], dtype=uint8)

In [8]:
print(img_colour)

[[[102 102 253]
  [107  93  14]
  [ 65 149  61]
  [ 54  54 255]
  [116 125 143]]

 [[107  93  14]
  [243 125 217]
  [102 102 253]
  [243 125 217]
  [ 99 228 233]]

 [[ 65 149  61]
  [ 24  24  24]
  [164  32  63]
  [ 99 228 233]
  [ 59  96  26]]]


In [3]:
import numpy
import cv2
newImage = numpy.array([[101,28,3,49], [101,28,3,49], [101,28,3,49]])
cv2.imwrite("newgray.png", newImage)

True

In [2]:
import numpy
import cv2
newImage2 = numpy.array([[0,0,0,0], [0,0,0,0], [0,0,0,0]])

cv2.imwrite("newgray2.png", newImage2)

True